services:
    nginx:
        restart: always
        build: ./nginx
        image: mlflow_nginx
        container_name: mlflow_nginx
        ports:
            - "85:85"
        networks:
            - frontend
        depends_on:
            - web

    db:
        image: postgres:13.1
        networks:
            - backend
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        restart: always
        expose:
            - "5432"
        volumes:
            - type: bind
              source: ${MLFLOW_DB_PATH:-/mlflow_storage/db}
              target: /var/lib/postgresql/data

    web:
        restart: always
        build: ./mlflow
        image: mlflow_server
        container_name: mlflow_server
        depends_on:
            db:
                condition: service_started
        networks:
            - frontend
            - backend
        expose:
            - "5000"
        environment:
            - MLFLOW_HTTP_REQUEST_TIMEOUT=360
            - no_proxy=db
        volumes:
            - type: bind
              source: ${MLFLOW_ARTIFACTS_PATH:-/mlflow_storage/artifacts}
              target: /mlflow-artifacts
        command: >
            bash -c "
            mlflow db upgrade postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} ;
            mlflow server --backend-store-uri postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} --serve-artifacts --artifacts-destination /mlflow-artifacts --default-artifact-root mlflow-artifacts:/ --host 0.0.0.0 --gunicorn-opts "--log-level=debug --timeout=8000 --graceful-timeout=75 --keep-alive=3600"
            "

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge

# Useful sources:
#   https://towardsdatascience.com/deploy-mlflow-with-docker-compose-8059f16b6039
#   https://medium.com/noodle-labs-the-future-of-ai/introduction-to-mlflow-for-mlops-part-3-database-tracking-minio-artifact-storage-and-registry-9fef196aaf42
# Adapted in Oct 2026 to remove minio and instead use LFS