# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pull request testing

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: mlflow
      POSTGRES_USER: msdndfvk
      POSTGRES_PASSWORD: adfg3245
      AWS_ACCESS_KEY_ID: fdash
      AWS_SECRET_ACCESS_KEY: rstjDFH345!
      MLFLOW_S3_IGNORE_TLS: true

    steps:
    - uses: actions/checkout@v2
      with:  # required for GitPython checks https://github.com/actions/checkout/issues/124
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: create test .git in test project root
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        cd tests/data
        git init
        git add .
        git commit -m "Initial commit"
        sudo mkdir /test_local
        git remote add test_local /test_local/.git
        git remote -v
        git push -u test_local main
        cd ../..

    - name: print dir
      run: |
        sudo apt-get install -y tree
        tree

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov .
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: start MLOps server
      run: |
        docker compose -f mlflow_server/docker-compose.yml up -d --build

    - name: Sleep for 30 seconds to allow MLOps server to start
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: check mlflow server status
      run: |
        docker ps

    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
         set -o pipefail
         pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=mlops tests/ | tee pytest-coverage.txt ; echo $?

    - name: Pytest coverage
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml

    - name: Stop containers
      if: always()
      run: docker-compose -f mlflow_server/docker-compose.yml down
