# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CLI test

on:
  pull_request:

jobs:
  cli_test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.9' ]

#    env:
#      POSTGRES_DB: mlflow
#      POSTGRES_USER: msdndfvk
#      POSTGRES_PASSWORD: adfg3245
#      AWS_ACCESS_KEY_ID: fdash
#      AWS_SECRET_ACCESS_KEY: rstjDFH345!
#      MLFLOW_S3_IGNORE_TLS: true

    steps:
    - uses: actions/checkout@v2
      with:  # required for GitPython checks https://github.com/actions/checkout/issues/124
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y nvidia-cuda-toolkit
        python -m pip install --upgrade pip
        python setup.py install

#    - name: start MLOps server
#      run: |
#        mkdir -p ~/MLOps_data/mlflow_minio
#        mkdir -p ~/MLOps_data/mlflow_db
#        docker compose -f mlflow_server/docker-compose.yml up -d --build

    - name: Test CLI
      run: |
         mlops run -h
#
#    - name: Stop containers
#      if: always()
#      run: |
#        docker-compose -f mlflow_server/docker-compose.yml down
